//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 02:28:23 PM GMT 
//


package Examples;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rental complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rental">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vehicleId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="no_of_rent_days" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="penaltyFee" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rentPerDay" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalAmountPayable" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Rental {

    @XmlElement(required = true)
    protected BigInteger vehicleId;
    @XmlElement(required = true)
    protected BigInteger customerId;
    @XmlElement(name = "no_of_rent_days", required = true)
    protected BigInteger noOfRentDays;
    protected double penaltyFee;
    protected double rentPerDay;
    protected double totalAmountPayable;
    @XmlElement(required = true)
    protected String startdate;
    @XmlElement(required = true)
    protected String enddate;

    /**
     * Gets the value of the vehicleId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVehicleId() {
        return vehicleId;
    }

    /**
     * Sets the value of the vehicleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVehicleId(BigInteger value) {
        this.vehicleId = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerId(BigInteger value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the noOfRentDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoOfRentDays() {
        return noOfRentDays;
    }

    /**
     * Sets the value of the noOfRentDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoOfRentDays(BigInteger value) {
        this.noOfRentDays = value;
    }

    /**
     * Gets the value of the penaltyFee property.
     * 
     */
    public double getPenaltyFee() {
        return penaltyFee;
    }

    /**
     * Sets the value of the penaltyFee property.
     * 
     */
    public void setPenaltyFee(double value) {
        this.penaltyFee = value;
    }

    /**
     * Gets the value of the rentPerDay property.
     * 
     */
    public double getRentPerDay() {
        return rentPerDay;
    }

    /**
     * Sets the value of the rentPerDay property.
     * 
     */
    public void setRentPerDay(double value) {
        this.rentPerDay = value;
    }

    /**
     * Gets the value of the totalAmountPayable property.
     * 
     */
    public double getTotalAmountPayable() {
        return totalAmountPayable;
    }

    /**
     * Sets the value of the totalAmountPayable property.
     * 
     */
    public void setTotalAmountPayable(double value) {
        this.totalAmountPayable = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartdate(String value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnddate(String value) {
        this.enddate = value;
    }

}
